//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int LogId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public string Area { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string Details { get; set; }
    
        public virtual User User { get; set; }
    }
}
