//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentPrediction
    {
        public int PredictionId { get; set; }
        public System.DateTime PredictionDate { get; set; }
        public int PredictedCount { get; set; }
        public Nullable<decimal> ConfidenceScore { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
